### Получение списка рецептов
GET http://localhost:8080/recipe

### Получение списка ингредиентов
GET http://localhost:8080/ingredient

### Получение рецепта по id
GET http://localhost:8080/recipe/0

### Получение ингредиента по id
GET http://localhost:8080/ingredient/0

### Добавление рецепта
POST http://localhost:8080/recipe
Content-Type: application/json

{
  "name": "Сырники из творога",
  "timeOfCook": 30,
  "ingredients": [
    {
      "name": "Творог",
      "count": 350,
      "measure": "г."
    },
    {
      "name": "Куриное яйцо",
      "count": 2,
      "measure": "гр."
    },
    {
      "name": "Пшеничная мука",
      "count": 100,
      "measure": "ст.л."
    },
    {
      "name": "сахар",
      "count": 2,
      "measure": "ст.л."
    }
  ],
  "steps": [
    "1: Смешайте весь творог с яйцами, сахаром и тщательно всё перемешайте",
    "2: Всыпьте в творог муку и тщательно перемешайте",
    "3: Поставьте сковороду на средний огонь и налейте в нее подсолнечное масло",
    "4: Слепите несколько небольших шариков из получившейся творожной массы и положите их на тарелку. Затем по очереди обкатывайте творожные шарики в муке и выкладывайте на сковороду",
    "5: Обжаривайте сырники 1–2 минуты до появления золотистой корочки. Затем переверните их на другую сторону и также обжарьте до золотистого состояния",
    "6: Повторяйте, пока творог не закончится"
  ]
}

### Добавление ингредиента
POST http://localhost:8080/ingredient
Content-Type: application/json

{
  "name": "Творог",
  "count": 350,
  "measure": "г."
}

### Редактирование рецепта по id
PUT http://localhost:8080/recipe/0
Content-Type: application/json

{
  "name": "Сырники из творога со скрипатой",
  "timeOfCook": 5,
  "ingredients": [
    {
      "name": "Натуральный творог старый",
      "count": 350,
      "measure": "г."
    },
    {
      "name": "Куриное яйцо протухшее",
      "count": 2,
      "measure": "гр."
    },
    {
      "name": "Пшеничная мука с жуками",
      "count": 100,
      "measure": "ст.л."
    },
    {
      "name": "песок речной",
      "count": 2,
      "measure": "ст.л."
    }
  ],
  "steps": [
    "1: Смешайте весь творог с яйцами, сахаром и тщательно всё перемешайте",
    "2: Всыпьте в творог муку и тщательно перемешайте",
    "3: Поставьте сковороду на средний огонь и налейте в нее подсолнечное масло",
    "4: Слепите несколько небольших шариков из получившейся творожной массы и положите их на тарелку. Затем по очереди обкатывайте творожные шарики в муке и выкладывайте на сковороду",
    "5: Обжаривайте сырники 1–2 минуты до появления золотистой корочки. Затем переверните их на другую сторону и также обжарьте до золотистого состояния",
    "6: Повторяйте, пока творог не закончится",
    "7: Ешьте, не обляпайтесь, приятного аппетита )))"
  ]
}

### Редактирование ингредиента по id
PUT http://localhost:8080/ingredient/0
Content-Type: application/json

{
  "name": "Творог",
  "count": 249,
  "measure": "г."
}

### Удаление рецепта по id
DELETE http://localhost:8080/recipe/0

### Удаление ингредиента по id
DELETE http://localhost:8080/ingredient/0